-- ============================================================
--  JP MÁQUINAS · Esquema do banco + Segurança (RLS)
--  Cole TUDO de uma vez no SQL Editor do projeto "jp-maquinas".
--  É re-executável: usa IF NOT EXISTS e DROP POLICY IF EXISTS.
-- ============================================================

-- ───────────────────────────────────────────────────────────
-- 1) TABELAS
--    Colunas inferidas a partir do que o sistema lê/grava.
--    empresa_codigo identifica a loja (Itabira / Manhuaçu / Irupi).
-- ───────────────────────────────────────────────────────────

create table if not exists public.bd_empresas (
  codigo text primary key,
  nome   text
);

-- De:Para — mapeia a conta do Citel para a linha/grupo da DRE
create table if not exists public.bd_plano_contas (
  id         bigint generated by default as identity primary key,
  codigo     text,            -- código da conta no Citel
  nome_citel text,            -- nome da conta no Citel
  dre_grupo  text,            -- ex.: RECEITAS BRUTA, DESPESAS FIXAS...
  dre_linha  text,            -- ex.: 01_ROP.A VISTA LOJA
  dre_ordem  integer,         -- ordem de exibição na DRE
  exibir_dre boolean default true,
  tipo       text
);

create table if not exists public.bd_titulos_pagos (
  id               bigint generated by default as identity primary key,
  empresa_codigo   text,
  data_pagamento   date,
  data_vencimento  date,
  duplicata        text,
  fornecedor       text,
  historico        text,
  plano_contas_cod text,
  centro_custo     text,
  valor            numeric(15,2),
  importado_em     timestamptz default now()
);

create table if not exists public.bd_titulos_recebidos (
  id               bigint generated by default as identity primary key,
  empresa_codigo   text,
  data_recebimento date,
  cliente          text,
  historico        text,
  portador         text,
  valor_recebido   numeric(15,2),
  valor_liquido    numeric(15,2),
  importado_em     timestamptz default now()
);

create table if not exists public.bd_vendas_markup (
  id             bigint generated by default as identity primary key,
  mes            date,
  empresa_codigo text,
  vr_total       numeric(15,2),
  vr_custo       numeric(15,2),
  resultado      numeric(15,2),
  pct_margem     numeric(15,4),
  unique (mes, empresa_codigo)   -- exigido pelo upsert (on_conflict)
);

create table if not exists public.bd_dre_receita_liquida (
  id              bigint generated by default as identity primary key,
  mes             date,
  empresa_codigo  text,
  receita_liquida numeric(15,2),
  vr_custo        numeric(15,2),
  unique (mes, empresa_codigo)   -- exigido pelo upsert (on_conflict)
);

create table if not exists public.bd_saldos_bancarios (
  id             bigint generated by default as identity primary key,
  ano            integer,
  mes            integer,       -- 1 a 12
  empresa_codigo text,
  saldo_final    numeric(15,2),
  observacao     text,
  unique (ano, mes, empresa_codigo)
);

-- ───────────────────────────────────────────────────────────
-- 2) LIGAR RLS EM TODAS AS TABELAS
--    Com RLS ligado e SEM policy para o papel anônimo, a chave
--    anon (pública, que fica no HTML) deixa de ler/escrever dados.
-- ───────────────────────────────────────────────────────────
alter table public.bd_empresas            enable row level security;
alter table public.bd_plano_contas        enable row level security;
alter table public.bd_titulos_pagos       enable row level security;
alter table public.bd_titulos_recebidos   enable row level security;
alter table public.bd_vendas_markup        enable row level security;
alter table public.bd_dre_receita_liquida  enable row level security;
alter table public.bd_saldos_bancarios     enable row level security;

-- ───────────────────────────────────────────────────────────
-- 3) POLICIES
--    Qualquer usuário AUTENTICADO (logado via Supabase Auth)
--    pode ler e gravar. Anônimo continua bloqueado.
--    Evolução futura (segmentar por loja): trocar "using (true)"
--    por algo como  using (empresa_codigo = (auth.jwt() ->> 'loja')).
-- ───────────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'bd_empresas','bd_plano_contas','bd_titulos_pagos','bd_titulos_recebidos',
    'bd_vendas_markup','bd_dre_receita_liquida','bd_saldos_bancarios'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', t || '_auth_all', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      t || '_auth_all', t);
  end loop;
end $$;

-- ───────────────────────────────────────────────────────────
-- 4) GRANTS — garante o acesso do papel "authenticated"
--    (o papel "anon" fica de fora; somado ao RLS acima, os dados
--     só aparecem depois do login)
-- ───────────────────────────────────────────────────────────
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================
--  FIM. Depois de rodar:
--   • a chave anon sozinha não acessa mais nenhum dado;
--   • o login (Supabase Auth) passa a ser a porta de entrada;
--   • importações e telas funcionam com o usuário logado.
-- ============================================================
